/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-present by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */

package ti.appsflyer

import com.appsflyer.AppsFlyerLib
import org.appcelerator.kroll.KrollModule
import org.appcelerator.kroll.KrollDict
import org.appcelerator.kroll.annotations.Kroll
import org.appcelerator.kroll.common.Log
import org.appcelerator.titanium.TiApplication

@Kroll.module(name = "TitaniumAppsFlyer", id = "ti.appsflyer")
class TitaniumAppsFlyerModule: KrollModule() {

	@Kroll.method
	fun initialize(params: KrollDict) {
		val devKey = params.getString("devKey")
		AppsFlyerLib.getInstance().init(devKey, null, TiApplication.getInstance().applicationContext)
	}

	@Kroll.method
	fun start() {
		AppsFlyerLib.getInstance().start(TiApplication.getInstance().applicationContext)
	}

	@Kroll.method
	fun logEvent(eventName: String, parameters: KrollDict) {
		AppsFlyerLib.getInstance().logEvent(TiApplication.getInstance().applicationContext, eventName, parameters)
	}

	@Kroll.getProperty
	fun idfa(): String {
		Log.e("TiAppsFlyer", "The \"idfa\" property is iOS-only!")
		return ""
	}
}
